import type { Metadata } from "next";
import "./globals.css";
import localFont from "@next/font/local";

export const metadata: Metadata = {
  title: "Kiddu",
  description: "Generated by create next app",
};

const alistaBlair = localFont({
  src: [
    {
      path: "../../public/fonts/Fredoka-Bold.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Fredoka_Condensed-Bold.ttf",
      weight: "600",
    },
  ],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={alistaBlair.variable}>{children}</body>
    </html>
  );
}
